### ISSUE TITLE
Rend2: Dark shaded triangles on player models

### ISSUE THREAD

**Issue by DT85** [xycaleth/OpenJK#20] opened 2015-07-21 11:13 UTC
Dark shaded triangles on player models that are randomised. Sometimes they show, sometimes they don't.

**Comment by xycaleth** [comment] 2015-07-23 22:10
Not sure how I'm going to fix this one. I'm unable to reproduce the same issue with my AMD card :( As far as I know, it's only happening on Nvidia cards.

**Comment by DT85** [comment] 2015-07-24 04:11
And it looks to only happen on ghoul2 models. MD3 is unaffected.

**Comment by xycaleth** [comment] 2015-07-25 12:10
Fixed in 7289d015. Silly mistake :p

**Closed by xycaleth** 2015-07-25 12:10 UTC
